PUSTAKAM/MYSITE/MYSITE/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('blog.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('review/',user_views.review, name='review'),
    path('thankyou/',user_views.thankyou, name='thankyou'),
    
    path('showfeedback/',user_views.showfeedback, name='showfeedback'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PUSTAKAM/MYSITE/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='blog-home'),
    path('booklist/',views.booklist,name='booklist'),
    path('about/', views.about,name='blog-about'),
    path('blog/search/',views.search, name='search'),
    path('book/<int:id>', views.bookdetail, name='bookdetail'),
    path('writerlist/',views.writerlist,name='writerlist'),
    path('writer/<int:id>', views.writerdetail, name='writerdetail'),
    path('book/<int:id>/comment/', views.comments, name='comments'),
    path('Genres/<int:id>', views.Genres, name='Genres'),
    path('contact/',views.contact,name='contact')
]

PUSTAKAM/MYSITE/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Homepage(models.Model):
    image = models.ImageField(default='default.jpg', upload_to='genre_pics')
    genre = models.ManyToManyField('Genre', help_text="Select a genre for this book")

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    

class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
        )
   
    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    image = models.ImageField(default='default.jpg', upload_to='book_pics')
    title = models.CharField(max_length=200)
    publication = models.CharField(max_length=200,default='none')
    the_writer = models.ManyToManyField('Writer', help_text="Select a genre for this book")
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    bookreview =  models.TextField(max_length=1000, default='enter your review here')
    the_genre = models.ManyToManyField('Genre', help_text="Select a genre for this book")
    buying_link = models.CharField(max_length=500,default='link')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    date_posted = models.DateTimeField(default=timezone.now)

   
    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([the_genre.name for the_genre in self.the_genre.all()[:3]])
    display_genre.short_description = 'Genre'
    
    def display_writer(self):
        return ', '.join([the_writer.name for the_writer in self.the_writer.all()[:3]])
    
    def display_language(self):
        return ', '.join([language.name for language in self.language.all()[:3]])
    
    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('bookdetail', args=[str(self.id)])

    
    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.title
        

class Writer(models.Model):
    """Model representing an author."""
    name = models.CharField(max_length=200)
    penname = models.CharField(max_length=200,default='None')
    image = models.ImageField(default='default.jpg', upload_to='writer_pics')
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)
    Bio=models.CharField(max_length=2000)
    knowmore=models.CharField(max_length=300,default='none')

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('writerdetail', args=[str(self.id)])
    

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Comment(models.Model):
    book = models.ForeignKey('blog.Book',on_delete=models.CASCADE)
    username =  models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    text = models.TextField(max_length=200,default='enter your comment here' )
    created_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.text
   




    

PUSTAKAM/MYSITE/blog/forms.py
from django import forms
from .models import Comment,Book

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

PUSTAKAM/MYSITE/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.template import loader
from .models import Book,Writer,Genre,Language,Homepage,Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def home(request):
    context = {
        'genres':Homepage.objects.all()
    }
    return render(request, 'home.html',context)


def booklist(request):
    context = {
        'books': Book.objects.all()
        }
    
    return render(request, 'booklist.html', context)

def writerlist(request):
    context = {
        'writers': Writer.objects.all()
    }
    return render(request, 'writerlist.html', context)


def about(request):
    return render(request, 'about.html', {'title': 'About'})



def bookdetail(request, id):
    
     book= Book.objects.get(id=id)

     return render(request, 'bookdetail.html',{'book': book})


def writerdetail(request, id):
    
    writer = Writer.objects.get(id=id)
                 
    return render(request, 'writerdetail.html',{'writer': writer})


@login_required
def comments(request, id):
    book = Book.objects.get(id=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.username= request.user
            comment.book = book
            comment.save()
            return redirect('bookdetail', id=book.id)
            
        
    else:
          form = CommentForm()

    return render(request, 'comments.html', {'form': form})


def Genres(request, id):
    genres = Genre.objects.get(id=id)
    return render(request, 'genrebooklist.html',{'genre': genres})

def search(request):
    text_search = request.GET.get("in")
    booklist= Book.objects.filter(title__icontains= text_search)
    writerlist=Writer.objects.filter(name__icontains=text_search)
    return render(request,'search.html',{'booklist':booklist ,'writerlist':writerlist})


def contact(request):
     return render(request, 'contact.html', {'title': 'Gallery'})







        

PUSTAKAM/MYSITE/blog/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h1>About Us</h1>
	<br/><br/>
	 <div class="container-fluid" style="background-color:black;opacity:0.8;width:1200px;color:orange">
	<h2 style="color:white;font-family:bookman old style">Hello Reader,</h2><br/>
	<p style="font-family:cairo;font-size:25px">Here in this website you will find all details about books and their authors.
	You can search books as per your favourite genre.You can also read the summary of the book and our review on that.You will also get the buying link of that book.
	You can comment down your opinion on that book.For commenting you only have to register and log in to your account.In the Books section you will find all books and in the Authors section 
	you will find about authors including books written by them and a short biography of the respective author.So,without wasting time anymore,let's get into the amezing world of Literature.</p>
	<p style="font-family:cairo;font-size:25px">Happy Reading !!!</p>
	<br/>
	<h2 style="color:white;font-family:bookman old style">Team BOOKWORM</h2>
	</div>
	<br/><br/><br/><br/>
	
	<div class="container" style="width:1200px;background-color:white;opacity:0.9">
	<h1 style="text-align:center;font-size:50px">Our Team</h1>
	<br/>
	<head>
<style>
* {
  box-sizing: border-box;
}

.column {
  float: left;
  width: 33.33%;
  padding:15px;
}

/* Clearfix (clear floats) */
.row::after {
  content: "";
  clear: both;
  display: table;
}
</style>
</head>
<div class="row" style="text-align:center;width:1200px">
  <div class="column">
            <div class="container-fluid" style="width:400px">
            <img style="width:200px;height:200px;border-radius:50%;margin-top:20px;border:5px solid black" src="/media/goovindjee.jpeg">
            <h2 class ="article-content" style="color:blue;font-family:bookman old style">Govind Jee<br/><i style="color:crimson">Developer<br/>Content Writer</i></h2>  
            </div>
  </div>
  <div class="column">
            <div class="container-fluid" style="width:300px">
            <img style="width:200px;height:200px;border-radius:50%;margin-top:20px;border:5px solid black" src="/media/default.jpg">
            <h2 class ="article-content" style="color:blue;font-family:bookman old style">ABC<br/><i style="color:crimson">Developer</i></h2>  
            </div>
  </div>
  <div class="column">
            <div class="container-fluid" style="width:300px">
            <img style="width:200px;height:200px;border-radius:50%;margin-top:20px;border:5px solid black" src="/media/default.jpg">
            <h2 class ="article-content" style="color:blue;font-family:bookman old style">XYZ<br/><i style="color:crimson">Developer</i></h2>  
            </div>
  </div>
</div>
</div>
<br/>
{% endblock content %}

PUSTAKAM/MYSITE/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}BOOKWORM{% endblock %}</title>


    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <style>
        h1 {
            color: #000000;
            font-family: 'Lobster';
        }
    </style>
</head>

<body style="background: url('/media/stack-of-books-vintage-books-book-books.jpg'); background-repeat: no-repeate; ">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">



            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <!-- Header -->

                    {% if user.is_authenticated %}<li><img src="{{user.profile.image.url}}" width="50"
                            style="border-radius:50%"></li>{% endif %}

                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'blog-home' %}"
                            style="font-family:arial;color:white;font-size:30px"><b>&nbsp &nbsp BOOKWORM</b></a>
                    </div>
                    <li class="{% block authors_active %}{% endblock %}"><a href="{% url 'writerlist' %}"><span
                                class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Authors</a></li>
                    <li class="{% block books_active %}{% endblock %}"><a href="{% url 'booklist' %}"><span
                                class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Books</a></li>

                    <form id="search" class="navbar-form navbar-left" role="search" method="get" action="blog/search">
                        <div class="form-group">
                            <input type="text" id="search_input" class="form-control" name="in">
                        </div>
                        <button type="submit" onclick="event_handler()" class="btn btn-default">Search</button>
                    </form>

                    {% if user.is_authenticated %}
                    <li><a href="{% url 'blog-home' %}">Home</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    <li><a href="{% url 'blog-about' %}">About Us</a></li>
                    <!--<li><a href="#">Gallery</a></li>-->
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'review' %}">Feedback</a></li>
                    {% else %}
                    <li><a href="{% url 'blog-home' %}">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Home</a>
                    <li><a href="{% url 'login' %}">Login</a>
                    <li><a href="{% url 'register' %}">Register</a>
                    <li><a href="{% url 'blog-about' %}">About Us</a>
                        <!-- <li><a href="#">Gallery</a></li>-->
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'review' %}">Feedback</a></li>
                    {% endif %}


                </ul>



            </div>

        </div>
    </nav>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    <b>{{message}}</b>
                </div>
                {% endfor %}
                {% endif %}
                {% block content %} {% endblock content %}
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    {% block javascript %}{% endblock %}

    <br /><br />


    <!--footer-->
    <footer id="footer">
        <style>
            .footer {
                position: relative;
                left: 0;
                bottom: 0;
                width: 100%;
                background-color: black;
                color: white;
                text-align: center;
            }

            .fa {
                padding: 15px;
                font-size: 20px;
                width: 50px;
                border-radius: 50%;
                text-align: center;
                text-decoration: none;
                margin: 5px 3px;
            }

            .fa:hover {
                opacity: 0.7;
            }

            .fa-facebook {
                background: #3B5998;
                color: white;
            }

            .fa-twitter {
                background: #55ACEE;
                color: white;
            }

            .fa-instagram {
                background: #125688;
                color: white;
            }

            .fa-linkedin {
                background: #007bb5;
                color: white;
            }
        </style>
        <div class="footer" style="text-align:left;">&nbsp &nbsp &nbsp <a style="color:white">Connect Us On:</a>
            <a href="https://www.facebook.com/profile.php?id=100006980441407" target="_blank" class="fa fa-facebook"></a>
            <a href="https://mobile.twitter.com/singh89555" target="_blank" class="fa fa-twitter"></a>
            <a href="https://www.instagram.com/govind.singh2199/" target="_blank" class="fa fa-instagram"></a>
            <a href="https://www.linkedin.com/mwlite/in/govind-singh-034b601a4" target="_blank" class="fa fa-linkedin"></a> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            © 2019 Copyright. All Rights Reserved.
        </div>
    </footer>
    <script>
        const event_handler = () => {
            const form_value = document.getElementById('search_input');
            if(form_value.value === ""){
                location.reload();
            }
        }
    </script>
</body>

</html>

PUSTAKAM/MYSITE/blog/templates/bookdetail.html
{% extends "base.html" %}
{% block content %}


	<div class="wrapper"style="width:900px;margin-left:100px;margin-top:50px">
       <!--<article class="media content-section">-->
		    <div class="media-body" style="text-align:left;"id="one">
              <div class="article-metadata">
              <!--<a class="mr-2" href="#">{{ book.author }}</a>-->
                  <small class="text-muted" style="color:black">{{ book.date_posted }}</small>
              </div>
			
			
			      <img style="width:300px;height:300px;border:5px solid black" src="{{book.image.url}}">
		    </div>
		
		<div class="media-body" id="two" style="width:30600px;color:black;text-align:left;background-color:white;opacity:0.9">
		    <div style="margin-left:30px;margin-right:30px">
			
			<h2><span><strong>Title:&nbsp </strong><b style="color:red">{{ book.title }}</b></h2>
			<h3><strong>Author:&nbsp </strong><b><i>{% for writer in book.the_writer.all %}
			<a style="color:darkskyblue" href="{% url 'writerdetail' writer.id %}">{{ writer.name }}</a>{% endfor %}</i></b><br/><br/>
            <p class="article-content"><strong>Genre:&nbsp </strong><i style="color:purple">
			{% for the_genre in book.the_genre.all %}{{the_genre}},&nbsp {% if not forloop.last %}{% endif %}{% endfor %}</i></p>  
			<p class="article-content"><strong>Publication:&nbsp </strong><i style="color:crimson">{{book.publication}}</i></p> 
			<p class="article-content"><strong>Language:&nbsp </strong><i style="color:green">{{ book.language }}</i></p>
			<br/><br/>
			<p class="article-content"><strong>You can buy the book &nbsp </strong><b><i><a href="{{ book.buying_link }}">Here</a></i></b>
			
			</div>
			
		</div>
		<br/><br/>
		<div class="container-fluid" style="width:900px;background-color:black;color:white;opacity:0.8">
		<h3 class="article-content"><strong>Summary:&nbsp</strong><i style="color:orange">{{ book.summary }}</i></h3><br/><br/>
		</div>
		<br/><br/>
		<div class="container-fluid" style="width:900px;background-color:black;color:white;opacity:0.8">
		<h3 class="article-content"><strong>Our Review:&nbsp</strong><i style="color:orange">{{ book.bookreview }}</i></h3>
		</div>	
        <!--</article>-->
	</div>	
	<br/><br/>
	<br/><br/>

<h1>Comments</h1>

<span>
<a class="btn btn-default" href="{% url 'comments' id=book.id %}">Add comment</a>
</span>
<br/><br/>
{% if book.comment_set.all %}
{% for comment in book.comment_set.all %}
	<div class="comments" style="background-color:white;margin-top:20px;opacity:0.9;height:100px">
        <p style="margin-left:10px;font-family:arial;font-size:20px;color:blue;margin-top:30px">
        <img style="height:30px;width:30px;border-radius:40%" src="{{comment.username.profile.image.url}}">&nbsp &nbsp<b>{{ comment.username }}&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  {{comment.created_date}} </b>
		
        <p/>
		<p style="margin-left:10px;font-family:arial;font-size:20px;color:black">
		<i>{{ comment.text}}</i>
		</p>
		<br/><br/>
    </div>
    {% endfor %}
{% endif %}
<br/><br/>
{% endblock content %}

PUSTAKAM/MYSITE/blog/templates/booklist.html
{% extends "base.html" %}
{% block content %}
    
	<h1>All Books</h1>
	
	{% for book in books %}
	
	
	
 <div class="wrapper" style="width:900px;height:200px;margin-left:100px;margin-top:50px">
       <!--<article class="media content-section">-->
	   <hr>
		    <div class="media-body" style="text-align:left;"id="one">
              <div class="article-metadata">
              <!--<a class="mr-2" href="#">{{ book.author }}</a>-->
                  <small class="text-muted" style="color:black">{{ book.date_posted }}</small>
              </div>
			
			
			      <img style="width:200px;height:200px;border:5px solid black" src="{{book.image.url}}">
		    </div>
		
		<div class="media-body" id="two" style="width:20600px;text-align:left;background-color:black;opacity:0.8">
		    <div style="margin-left:30px;margin-right:30px;">
		    <h2><strong style="color:orange">Title: </strong><a style="color:white" href="{% url 'bookdetail' id=book.id %}">{{ book.title}}</a></h2>
            <h3><strong style="color:orange">Author: </strong>{% for writer in book.the_writer.all %}<a href="{% url 'writerdetail' writer.id %}">{{ writer.name }}</a>{% endfor %}
            <br/><br/>
			<h3><a href="{% url 'bookdetail' id=book.id %}"><strong>Read Details</strong></a></h3>
		    </div>
		</div>
		</hr>
			
        <!--</article>-->
</div>	
	<br/><br/><br/>
    {% endfor %}
{% endblock content %}

PUSTAKAM/MYSITE/blog/templates/comments.html
{% extends 'base.html' %}


{% block content %}

    <h1>New comment</h1>
	<h3>You are commenting as {{user.username}}<br/><br/>
	
    <form method="POST" class="post-form" >
	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
	<br/>
{% endblock %}

PUSTAKAM/MYSITE/blog/templates/contact.html
{% extends "base.html" %}
{% block content %}
    <h1>Contact Us</h1>
	<br/><br/>
	 <div class="container-fluid" style="background-color:black;opacity:0.8;width:1200px;color:orange">
	<h2 style="color:white;font-family:bookman old style">Hello Reader,</h2><br/>
	<p style="font-family:cairo;font-size:25px">You can contact us on our Email address for any query or 
     complaint. Our Email id is<a href="https://gmail.com">govind.singh2199@gmail.com</a>. Also you can follow us on 
	<a href="https://www.facebook.com/profile.php?id=100006980441407" target="_blank">Facebook</a>, <a href="https://www.instagram.com/govind.singh2199/" target="_blank">Instagram</a>, <a href="https://www.linkedin.com/mwlite/in/govind-singh-034b601a4" target="_blank">LinkedIn</a> or <a href="https://mobile.twitter.com/singh89555" target="_blank">Twitter</a>.<br/><br/> Please give your Feedback 
	by filling up the Feedback form from the navigation bar or from <a href="{% url 'review' %}">HERE.</a></p>
	<p style="font-family:cairo;font-size:25px">Happy Reading !!!</p>
	<br/>
	<h2 style="color:white;font-family:bookman old style">Team BOOKWORM</h2>
	</div>
	<br/>
{% endblock %}

PUSTAKAM/MYSITE/blog/templates/genrebooklist.html
{% extends "base.html" %}
{% block content %}

<h1> All &nbsp Books &nbsp of &nbsp "{{genre.name}}"</h1>

{% for book in genre.book_set.all %}

 <div class="wrapper" style="width:900px;height:200px;margin-left:100px;margin-top:50px">
       <!--<article class="media content-section">-->
	   <hr>
		    <div class="media-body" style="text-align:left;"id="one">
              <div class="article-metadata">
              <!--<a class="mr-2" href="#">{{ book.author }}</a>-->
                  <small class="text-muted" style="color:black">{{ book.date_posted }}</small>
              </div>
			
			
			      <img style="width:200px;height:200px;border:5px solid black" src="{{book.image.url}}">
		    </div>
		
		<div class="media-body" id="two" style="width:20600px;color:black;text-align:left;background-color:black;opacity:0.8">
		    <div style="margin-left:30px;margin-right:30px">
		    <h2><strong style="color:orange">Title: </strong><a style="color:white" href="{% url 'bookdetail' id=book.id %}">{{ book.title}}</a></h2>
            <h3><strong style="color:orange">Author: </strong>{% for writer in book.the_writer.all %}<a href="{% url 'writerdetail' writer.id %}">{{ writer.name }}</a>{% endfor %}
            <br/><br/>
			<h3><a href="{% url 'bookdetail' id=book.id %}"><strong>Read Details</strong></a></h3>
		    </div>
		</div>
		</hr>
			
        <!--</article>-->
</div>		
{% endfor %}
<br/><br/>
{% endblock content %}

PUSTAKAM/MYSITE/blog/templates/writerdetail.html
{% extends "base.html" %}
{% block content %}
<div class="wrapper"style="width:1000px;margin-left:80px;margin-top:50px">
       <!--<article class="media content-section">-->
		    <div class="media-body" style="text-align:left;"id="one">
              <img style="width:350px;height:350px;border:5px solid black" src="{{writer.image.url}}">
		    </div>
		
		<div class="media-body" id="two" style="width:30000px;color:black;text-align:left;background-color:white;opacity:0.8">
		    <div style="margin-left:30px;margin-right:20px">
		    <h2><strong>Name: </strong><b style="color:blue">{{writer.name}}</b></h2>
			<h2><strong>Pen Name: </strong><i style="color:red">{{writer.penname}}</i></h2><br/>
			<h3><strong>Date of Birth: </strong><i style="color:purple">{{writer.date_of_birth}}</i></h3>
			<h3><strong>Date of Death: </strong><i style="color:green">{{writer.date_of_death}}</i></h3><br/>
			<h3><strong><a href="{{ writer.knowmore }}"><b><i>Know more about the author</i></b></a></strong></h3>
			</div>
		</div>

<br/><br/>	
            <div class="container-fluid" style="width:1000px;background-color:black;color:white;opacity:0.8">
			<h3><strong>Books by the Writer:&nbsp </strong>
			<i style="color:orange">
           {% for book in writer.book_set.all %}
                <a href="{% url 'bookdetail' book.id %}">{{book.title}},&nbsp </a> 
           {% endfor %}
		   </i>
           </h3>
		   </div><br/><br/>
		   <div class="container-fluid" style="width:1000px;background-color:black;color:white;opacity:0.8">	
			<h3><strong>Bio:&nbsp </strong><i style="color:orange">{{writer.Bio}}</i></h3>
			</div>
			<br/><br/>
</div>
{% endblock content%}